name: Build Server
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'  # numeric SemVer tags

jobs:
  build:
    name: Build and Tag PyroKV Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # <-- required for workload identity federation

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate tag format (SemVer)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF##*/}"
          [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "Invalid tag: $TAG"; exit 1; }

      - name: Authenticate to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/760210923437/locations/global/workloadIdentityPools/automation-pool/providers/github-provider'
          service_account: 'github-service-account@pyrokv.iam.gserviceaccount.com'

      - name: Docker login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build Docker Image
        env:
          IMAGE_TAG: ${{ github.ref_name }}
          IMAGE_SHA: ${{ github.sha }}
        run: |
          docker build -t us-central1-docker.pkg.dev/pyrokv/pyrokv/pyrokv-server:${IMAGE_TAG} \
                       -t us-central1-docker.pkg.dev/pyrokv/pyrokv/pyrokv-server:${IMAGE_SHA} \
                       -t us-central1-docker.pkg.dev/pyrokv/pyrokv/pyrokv-server:latest \
                       -t pyrokv:${IMAGE_TAG} \
                       -t pyrokv:${IMAGE_SHA} \
                       -t pyrokv:latest \
                       -f crates/pyrokv-server/Dockerfile .

      - name: Push to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/pyrokv/pyrokv/pyrokv-server --all-tags
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        env:
          IMAGE_TAG: ${{ github.ref_name }}
          IMAGE_SHA: ${{ github.sha }}
        run: |
          docker tag pyrokv:${IMAGE_TAG} ${DOCKER_HUB_USERNAME}/pyrokv:${IMAGE_TAG}
          docker tag pyrokv:${IMAGE_SHA} ${DOCKER_HUB_USERNAME}/pyrokv:${IMAGE_SHA}
          docker tag pyrokv:latest ${DOCKER_HUB_USERNAME}/pyrokv:latest
          docker push ${DOCKER_HUB_USERNAME}/pyrokv --all-tags
